# version: "4"

services:
  lynkpage-frontend:
    build:
      dockerfile: Dockerfile
      args:
        - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL}
        - NUXT_PUBLIC_HOME_URL=${NUXT_PUBLIC_HOME_URL}
    image: lynkpage-frontend
    restart: always
    ports:
      - "3000:3000"
