# version: "4"

services:
  lynkpage-frontend:
    build:
      dockerfile: Dockerfile
      args:
        # if the env is not set, the default value is used
        - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL:-http://localhost:8000}
        - NUXT_PUBLIC_HOME_URL=${NUXT_PUBLIC_HOME_URL:-http://localhost:3000}
    image: lynkpage-frontend
    restart: always
    ports:
      - "3000:3000"
