name: Deploy lynkpage client

on:
  workflow_run:
    workflows: [ci]
    branches: [main]
    types:
      - completed
      - passed


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.0"

      - name: Build and push Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          NUXT_PUBLIC_API_URL: ${{ secrets.NUXT_PUBLIC_API_URL }}
          NUXT_PUBLIC_HOME_URL: ${{ secrets.NUXT_PUBLIC_HOME_URL }}
        run: |
          gcloud auth configure-docker africa-south1-docker.pkg.dev
          # docker build -t gcr.io/GOOGLE_PROJECT/$IMAGE_NAME:$GITHUB_SHA .
          # Build the image
          docker compose build --parallel --no-cache
          # Tag the image
          docker tag lynkpage-frontend:latest africa-south1-docker.pkg.dev/$GOOGLE_PROJECT/lynkpage-frontend/lynkpage-frontend:$GITHUB_SHA
          # Push the image
          docker push africa-south1-docker.pkg.dev/$GOOGLE_PROJECT/lynkpage-frontend/lynkpage-frontend:$GITHUB_SHA
          # remove auth
          gcloud auth revoke --all
